name: fast-mcp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - numpy>=1.24.0
  - requests>=2.28.0
  - pip:
    - fastmcp==2.11
    - google-genai>=0.2.0
    - tinydb>=4.8.0